import type { SeedCourseData } from '../seed-data';

export const javaCourseData: SeedCourseData = {
  course: {
    id: 'course-java',
    slug: 'java-enterprise',
    title: 'Java Enterprise & JVM Systems',
    description: 'Master Java 21, JVM internals, Object-Oriented Architecture, Spring Boot 3, Streams API, and high-concurrency enterprise services.',
    technology: 'Java',
    category: 'Programming Languages',
    level: 'INTERMEDIATE',
    estimatedHours: 45,
    published: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  chapters: [
    {
      id: 'chap-java-1',
      courseId: 'course-java',
      title: 'Java Core & JVM Architecture',
      description: 'Bytecode, classloaders, garbage collection basics, primitive types, and operators.',
      order: 1,
      level: 'BASIC',
      lessons: [
        {
          id: 'les-java-1',
          chapterId: 'chap-java-1',
          slug: 'jvm-architecture-and-setup',
          title: 'JVM, JRE, JDK & Bytecode Execution',
          description: 'Understanding the JVM runtime data areas, ClassLoader hierarchy, and modern Java 21 LTS.',
          duration: 20,
          order: 1,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Differentiate between JDK, JRE, and the Java Virtual Machine (JVM).
- Compile source files with \`javac\` and inspect generated bytecode with \`javap\`.

\`\`\`java
public class Welcome {
    public static void main(String[] args) {
        System.out.println("Welcome to Java Enterprise on EduCode Academy!");
        System.out.println("Runtime Version: " + System.getProperty("java.version"));
    }
}
\`\`\`
`,
        },
        {
          id: 'les-java-2',
          chapterId: 'chap-java-1',
          slug: 'primitive-types-and-operators',
          title: 'Primitive Types, Reference Types & Wrapper Classes',
          description: 'Stack vs Heap allocation, autoboxing, unboxing, and bitwise operators.',
          duration: 20,
          order: 2,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Understand stack vs heap allocation for primitives vs objects.

\`\`\`java
public class DataRepresentation {
    public static void main(String[] args) {
        int primitiveNumber = 42;
        Integer boxedNumber = Integer.valueOf(42); // Autoboxing
        System.out.println("Equal value: " + (primitiveNumber == boxedNumber));
    }
}
\`\`\`
`,
        },
        {
          id: 'les-java-3',
          chapterId: 'chap-java-1',
          slug: 'control-flow-and-enhanced-switch',
          title: 'Control Flow & Modern Enhanced Switch Expressions',
          description: 'If-else branching, while loops, for-each, and Java 17+ pattern matching switch expressions.',
          duration: 20,
          order: 3,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Write concise switch expressions that return values with \`yield\`.

\`\`\`java
public class SwitchDemo {
    public static String getRoleDescription(String role) {
        return switch (role.toUpperCase()) {
            case "ADMIN" -> "Full system access & user management";
            case "INSTRUCTOR" -> "Course creation & student grading";
            case "STUDENT" -> "Interactive learning & project submissions";
            default -> "Guest preview";
        };
    }
}
\`\`\`
`,
        },
        {
          id: 'les-java-4',
          chapterId: 'chap-java-1',
          slug: 'arrays-and-string-manipulation',
          title: 'Arrays, String Immutability & StringBuilder',
          description: 'String constant pool, memory efficiency, and multi-dimensional arrays.',
          duration: 20,
          order: 4,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Avoid memory thrashing by using \`StringBuilder\` for iterative string concatenation.

\`\`\`java
public class StringPoolDemo {
    public static void main(String[] args) {
        StringBuilder sb = new StringBuilder();
        for (int i = 1; i <= 5; i++) {
            sb.append("Lesson ").append(i).append("; ");
        }
        System.out.println(sb.toString());
    }
}
\`\`\`
`,
        },
        {
          id: 'les-java-5',
          chapterId: 'chap-java-1',
          slug: 'methods-and-varargs',
          title: 'Methods, Method Overloading & Varargs',
          description: 'Pass-by-value semantics, method signatures, recursion, and variable arguments.',
          duration: 20,
          order: 5,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Design clean method signatures and understand pass-by-value with object references.

\`\`\`java
public class MathUtil {
    public static double average(double... values) {
        if (values.length == 0) return 0.0;
        double sum = 0;
        for (double v : values) sum += v;
        return sum / values.length;
    }
}
\`\`\`
`,
        },
      ],
    },
    {
      id: 'chap-java-2',
      courseId: 'course-java',
      title: 'Object-Oriented Programming in Java',
      description: 'Classes, encapsulation, inheritance, interfaces, and polymorphism.',
      order: 2,
      level: 'INTERMEDIATE',
      lessons: [
        {
          id: 'les-java-6',
          chapterId: 'chap-java-2',
          slug: 'classes-objects-and-constructors',
          title: 'Classes, Objects, Constructors & this Keyword',
          description: 'Field initialization, constructor chaining, and memory allocation.',
          duration: 25,
          order: 6,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Master class declaration and constructor chaining with \`this()\`.

\`\`\`java
public class UserAccount {
    private String username;
    private String email;

    public UserAccount(String username) {
        this(username, username + "@example.com");
    }

    public UserAccount(String username, String email) {
        this.username = username;
        this.email = email;
    }
}
\`\`\`
`,
        },
        {
          id: 'les-java-7',
          chapterId: 'chap-java-2',
          slug: 'inheritance-and-super',
          title: 'Inheritance, Method Overriding & super',
          description: 'Single inheritance, \`super\` invocations, and the \`final\` keyword.',
          duration: 25,
          order: 7,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Extend classes and enforce strict contracts with method overriding.

\`\`\`java
public class Employee {
    protected String name;
    public Employee(String name) { this.name = name; }
    public double calculateBonus() { return 1000.0; }
}

public class Manager extends Employee {
    public Manager(String name) { super(name); }
    @Override
    public double calculateBonus() { return super.calculateBonus() * 2.5; }
}
\`\`\`
`,
        },
        {
          id: 'les-java-8',
          chapterId: 'chap-java-2',
          slug: 'abstract-classes-and-interfaces',
          title: 'Abstract Classes vs Interfaces & Default Methods',
          description: 'Multiple interface implementation, default methods, and static methods.',
          duration: 25,
          order: 8,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Understand when to use abstract classes vs decoupled interfaces.

\`\`\`java
public interface PaymentGateway {
    boolean processPayment(String account, double amount);
    
    default void logTransaction(String txId) {
        System.out.println("Transaction logged: " + txId);
    }
}
\`\`\`
`,
        },
        {
          id: 'les-java-9',
          chapterId: 'chap-java-2',
          slug: 'polymorphism-and-instanceof',
          title: 'Polymorphism & Pattern Matching for instanceof',
          description: 'Dynamic method dispatch, safe casting, and modern pattern matching.',
          duration: 20,
          order: 9,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Use modern pattern matching for \`instanceof\` to remove casting boilerplate.

\`\`\`java
public class Dispatcher {
    public static void process(Object obj) {
        if (obj instanceof String s) {
            System.out.println("String length: " + s.length());
        } else if (obj instanceof Number n) {
            System.out.println("Double value: " + n.doubleValue());
        }
    }
}
\`\`\`
`,
        },
        {
          id: 'les-java-10',
          chapterId: 'chap-java-2',
          slug: 'java-records-and-sealed-classes',
          title: 'Java Records, Enums & Sealed Classes',
          description: 'Immutable data carriers with Records and domain modeling with Sealed Hierarchies.',
          duration: 25,
          order: 10,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Replace Lombok/boilerplate with Java 17+ Records.

\`\`\`java
public record CourseSummary(String id, String title, int estimatedHours, boolean certified) {}

public class Main {
    public static void main(String[] args) {
        CourseSummary course = new CourseSummary("J01", "Java Enterprise", 45, true);
        System.out.println(course.title() + " (" + course.estimatedHours() + "h)");
    }
}
\`\`\`
`,
        },
      ],
    },
    {
      id: 'chap-java-3',
      courseId: 'course-java',
      title: 'Collections Framework & Generics',
      description: 'Generics, Lists, Sets, Maps, Queues, and Comparator/Comparable.',
      order: 3,
      level: 'INTERMEDIATE',
      lessons: [
        {
          id: 'les-java-11',
          chapterId: 'chap-java-3',
          slug: 'java-generics-and-wildcards',
          title: 'Generics, Type Erasure & Wildcards (? extends / ? super)',
          description: 'Generic classes, bounded type parameters, and PECS rule (Producer Extends, Consumer Super).',
          duration: 25,
          order: 11,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Master type-safe generic containers and wildcards.

\`\`\`java
public class Box<T> {
    private T item;
    public void set(T item) { this.item = item; }
    public T get() { return item; }
}
\`\`\`
`,
        },
        {
          id: 'les-java-12',
          chapterId: 'chap-java-3',
          slug: 'list-arraylist-and-linkedlist',
          title: 'List Interface: ArrayList vs LinkedList',
          description: 'Time complexity, amortized array resizing, and iteration performance.',
          duration: 20,
          order: 12,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Choose the correct list implementation based on indexing vs insertion patterns.

\`\`\`java
import java.util.*;

public class ListDemo {
    public static void main(String[] args) {
        List<String> list = new ArrayList<>(List.of("Python", "Java", "Go"));
        list.add("Rust");
        System.out.println("First element: " + list.get(0));
    }
}
\`\`\`
`,
        },
        {
          id: 'les-java-13',
          chapterId: 'chap-java-3',
          slug: 'set-hashset-and-treeset',
          title: 'Set Interface: HashSet, LinkedHashSet & TreeSet',
          description: 'Hashcode contract, equals implementation, and red-black tree ordering in TreeSet.',
          duration: 20,
          order: 13,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Guarantee unique collections and implement consistent \`equals\` and \`hashCode\`.
`,
        },
        {
          id: 'les-java-14',
          chapterId: 'chap-java-3',
          slug: 'map-hashmap-and-concurrenthashmap',
          title: 'Map Interface: HashMap, TreeMap & ConcurrentHashMap',
          description: 'Buckets, collision resolution (linked list to treeify), and thread safety.',
          duration: 25,
          order: 14,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Understand internal hash bucket distribution and concurrency with \`ConcurrentHashMap\`.
`,
        },
        {
          id: 'les-java-15',
          chapterId: 'chap-java-3',
          slug: 'comparable-and-comparator',
          title: 'Sorting Collections: Comparable vs Comparator',
          description: 'Natural ordering vs custom sorting with lambda comparator chains.',
          duration: 20,
          order: 15,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Sort objects with lambda expressions and \`Comparator.comparing()\`.

\`\`\`java
import java.util.*;

record Student(String name, int score) {}

public class SortDemo {
    public static void main(String[] args) {
        List<Student> students = Arrays.asList(
            new Student("Somchai", 85),
            new Student("Anan", 92),
            new Student("Somsak", 78)
        );
        students.sort(Comparator.comparingInt(Student::score).reversed());
        students.forEach(s -> System.out.println(s.name() + ": " + s.score()));
    }
}
\`\`\`
`,
        },
      ],
    },
    {
      id: 'chap-java-4',
      courseId: 'course-java',
      title: 'Streams, Concurrency & Spring Boot',
      description: 'Functional programming, Streams API, Virtual Threads, and REST services.',
      order: 4,
      level: 'ADVANCED',
      lessons: [
        {
          id: 'les-java-16',
          chapterId: 'chap-java-4',
          slug: 'functional-interfaces-and-lambdas',
          title: 'Functional Interfaces & Lambda Expressions',
          description: 'Predicate, Function, Consumer, Supplier, and method references.',
          duration: 25,
          order: 16,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Leverage built-in functional interfaces in \`java.util.function\`.
`,
        },
        {
          id: 'les-java-17',
          chapterId: 'chap-java-4',
          slug: 'java-stream-api-pipeline',
          title: 'Stream API: Filter, Map, FlatMap & Collectors',
          description: 'Lazy evaluation, intermediate vs terminal operations, and groupingBy.',
          duration: 30,
          order: 17,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Build expressive data transformation pipelines with Java Streams.

\`\`\`java
import java.util.*;
import java.util.stream.Collectors;

public class StreamDemo {
    public static void main(String[] args) {
        List<String> names = List.of("java", "python", "golang", "rust");
        List<String> upper = names.stream()
            .filter(s -> s.length() > 4)
            .map(String::toUpperCase)
            .collect(Collectors.toList());
        System.out.println(upper);
    }
}
\`\`\`
`,
        },
        {
          id: 'les-java-18',
          chapterId: 'chap-java-4',
          slug: 'optional-and-exception-handling',
          title: 'Optional Class & Checked vs Unchecked Exceptions',
          description: 'Eliminating NullPointerExceptions and creating custom business exceptions.',
          duration: 25,
          order: 18,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Use \`Optional.ofNullable()\`, \`map()\`, \`orElseThrow()\` properly.
`,
        },
        {
          id: 'les-java-19',
          chapterId: 'chap-java-4',
          slug: 'multithreading-and-virtual-threads',
          title: 'Concurrency, ThreadPools & Java 21 Virtual Threads',
          description: 'ExecutorService, CompletableFuture, and Project Loom lightweight Virtual Threads.',
          duration: 30,
          order: 19,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Run millions of concurrent tasks using Java 21 Virtual Threads (\`Executors.newVirtualThreadPerTaskExecutor()\`).
`,
        },
        {
          id: 'les-java-20',
          chapterId: 'chap-java-4',
          slug: 'spring-boot-rest-controller',
          title: 'Spring Boot 3: REST Controllers & Dependency Injection',
          description: '@RestController, @GetMapping, @PostMapping, and @Autowired IoC container.',
          duration: 30,
          order: 20,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Build production-ready REST controllers with Spring Boot 3.

\`\`\`java
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@RequestMapping("/api/v1/courses")
public class CourseRestController {
    @GetMapping
    public List<String> listCourses() {
        return List.of("Java Enterprise", "Spring Boot", "Microservices");
    }
}
\`\`\`
`,
        },
        {
          id: 'les-java-21',
          chapterId: 'chap-java-4',
          slug: 'spring-data-jpa-and-hibernate',
          title: 'Spring Data JPA & Hibernate Repository Pattern',
          description: 'Entity mappings, CrudRepository, JpaRepository, and PostgreSQL connections.',
          duration: 30,
          order: 21,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Model database entities and query PostgreSQL with Spring Data JPA.
`,
        },
        {
          id: 'les-java-22',
          chapterId: 'chap-java-4',
          slug: 'testing-with-junit5-and-mockito',
          title: 'Testing with JUnit 5, Mockito & Maven/Gradle Build',
          description: 'Unit testing, mocking service dependencies, and containerizing with Docker.',
          duration: 25,
          order: 22,
          published: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          content: `## 🎯 Learning Objectives
- Write automated unit tests with JUnit 5 and Mockito.
`,
        },
      ],
    },
  ],
  projects: [
    {
      id: 'proj-java-1',
      courseId: 'course-java',
      title: 'Enterprise Inventory & Order Management System',
      description: 'Build a modular Java backend with Repository pattern, multi-threading concurrency control, and RESTful endpoints.',
      difficulty: 'ADVANCED',
      estimatedHours: 15,
      repositoryUrl: 'https://github.com/educode-academy/java-inventory-system',
      techStack: ['Java 21', 'Spring Boot 3', 'PostgreSQL', 'Maven', 'Docker'],
      steps: [
        {
          id: 'step-java-1',
          projectId: 'proj-java-1',
          title: '1. Domain Modeling & Repository Layer',
          description: 'Setup entity relationships and Spring Data JPA repositories.',
          order: 1,
          content: 'Define entities with proper constraints and audit fields.',
        },
      ],
    },
  ],
};
